name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'production'
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Install tools (for Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Install tools (for macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install coreutils
          brew install yq

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Bundler
        run: gem install bundler

      - name: Bundle Caching
        id: bundle-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          bundle install

      - name: Build Site
        env:
          PAGES_REPO_NWO: "hmkim312/hmkim312.github.io" # 본인의 사용자명과 저장소명으로 변경
        run: |
          JEKYLL_ENV=production bundle exec jekyll b -d _site
          
      - name: Test Site
        run: |
          bash tools/test.sh
